export const typeColors: Record<string, string> = {
    normal: "bg-gray-300 text-black",
    fire: "bg-red-500 text-white",
    water: "bg-blue-500 text-white",
    grass: "bg-green-500 text-white",
    electric: "bg-yellow-400 text-black",
    ice: "bg-cyan-300 text-black",
    fighting: "bg-red-700 text-white",
    poison: "bg-purple-500 text-white",
    ground: "bg-yellow-600 text-white",
    flying: "bg-sky-300 text-black",
    psychic: "bg-pink-400 text-black",
    bug: "bg-lime-500 text-black",
    rock: "bg-yellow-800 text-white",
    ghost: "bg-indigo-700 text-white",
    dark: "bg-gray-800 text-white",
    dragon: "bg-purple-800 text-white",
    steel: "bg-gray-400 text-black",
    fairy: "bg-pink-300 text-black",
  };